spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/online_store_db
    username: postgres
    password: My_passw0rd

  liquibase:
    enabled: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: trifanya.onlinestore@gmail.com
    password: puxhjgrhvwhypkjl
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
        debug: true


jwt:
  secret: 1qaz2wsx3edc4rfv5tgb6yhn7ujm8ik9ol0pldhgdlfjgoailsrgjxlk34wtrdgh
  lifetime: 30d
