spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/boot_security_db
    username: postgres
    password: Goalie_climber62
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
jwt:
  secret: secret_for_jwt
  lifetime: 30m
